// aeScript.js — per-shot After Effects (.jsx) handoff builder for VFX Pull (pure).
//
// AE project files (.aep) are a proprietary binary format that cannot be written
// from Node. The industry-standard handoff is an ExtendScript (.jsx) the artist
// runs in AE (File > Scripts > Run Script File, or `afterfx -r script.jsx`) to
// BUILD the per-shot comp. This is the AE analogue of nukeScript.js.
//
// The emitted comp mirrors the Nuke graph:
//   import EXR plate → comp at FDL canvas size → Time Remap (from the frame map)
//   → OCIO color (AP0→working, auto-match CDL, show LUT) → QT-ref guide layer.
//
// Corrections vs. the earlier standalone generate_ae.jsx:
//   • Reframe uses a UNIFORM scale + position (no non-uniform squash).
//   • Time Remap is driven by the resolved per-frame map (ramps already
//     integrated) instead of collapsing each segment to its start speed.
//   • Working space is set via the real `app.project.workingSpace` DOM property.
//   • All retime keyframes are baked into the script, so it has no runtime
//     dependency on reading a sidecar from disk.
//
// Pure string builder (no DOM / state) so it is unit-testable.
'use strict';

import { buildFrameMapJSON } from './pullJobModel.js';

function _esc(s) { return String(s == null ? '' : s).replace(/\\/g, '\\\\').replace(/"/g, '\\"'); }
function _num(v, d = 0) { const n = Number(v); return Number.isFinite(n) ? n : d; }

export function buildAeScript(job = {}, opts = {}) {
  const manifest = opts.manifest || {};
  const plateName = job.plateName || manifest.plateName || 'plate';
  const shotName  = manifest.shotName || job.shotId || 'shot';

  const first = _num(job.frameStart ?? manifest.frameStart ?? 1001, 1001);
  const count = Math.max(1, _num(manifest.frameCount ?? job.expectedRenderedFrameCount ?? job.frameCount ?? 1, 1));
  const fps   = _num(job.fps ?? 24, 24);

  // EXR sequence path (matches nukeScript's relative layout).
  const platePath = `${job.package?.exr || 'plates'}/${plateName}.[####].exr`;
  const colorspace = manifest.colorInfo?.exrColorSpace || job.colorPlan?.outputSpace || 'ACES2065-1';
  const workingSpace = 'ACEScg';

  // Target (FDL canvas) size — same resolution logic as nukeScript's Reformat.
  const reframe = job.reframe || {};
  const tw = _num(reframe.targetWidth  || manifest.resizeInfo?.timelineResolution?.width  || manifest.outputResolution?.split?.('x')?.[0], 1920);
  const th = _num(reframe.targetHeight || manifest.resizeInfo?.timelineResolution?.height || manifest.outputResolution?.split?.('x')?.[1], 1080);
  const baked = !!job.renderPlan?.bakeReframe;

  // Uniform geometry transform (NEVER non-uniform — that distorts the plate).
  const g = job.geometry || {};
  const uniformScale = _num(g.scale, 1) * 100;
  const posX = (tw / 2) + _num(g.positionX, 0);
  const posY = (th / 2) + _num(g.positionY, 0);

  // Time Remap keyframes (seconds) come from the canonical frame map so the AE,
  // Nuke and CSV/JSON artifacts all agree.
  const fm  = buildFrameMapJSON(job, manifest);
  const kfs = fm.shot?.ae_time_remap?.keyframes_seconds || [];
  const hasSpeedChange = !!job.retime?.hasSpeedChange;

  // Auto-match CDL (reference grade) + show LUT, mirroring the Nuke handoff.
  const cdl = job.color?.match?.cdl || null;
  const cdlSlope  = cdl ? `[${(cdl.slope  || [1, 1, 1]).join(', ')}]` : '[1,1,1]';
  const cdlOffset = cdl ? `[${(cdl.offset || [0, 0, 0]).join(', ')}]` : '[0,0,0]';
  const cdlPower  = cdl ? `[${(cdl.power  || [1, 1, 1]).join(', ')}]` : '[1,1,1]';
  const cdlSat    = cdl ? _num(cdl.sat ?? cdl.saturation, 1) : 1;
  const showLut   = (job.colorPlan?.luts || []).find(l => l && l.type === 'show_lut' && l.path);
  const showLutPath = job.colorPlan?.applyLook && showLut ? showLut.path : '';

  const qtRef = manifest.reviewMov || job.package?.reviewMov || '';

  // ── Emit the ExtendScript ──────────────────────────────────────────────────
  return `// PostFlowX — After Effects handoff for ${_esc(shotName)} / ${_esc(plateName)}
// Generated by PostFlowX VFX Pull. Run in AE:  File > Scripts > Run Script File
// (or headless:  afterfx -r "${_esc(plateName)}.jsx")
//
// Builds the per-shot comp with FDL framing, frame-map retime, and AMF color.
// Data is baked in below — no sidecar read required.

(function () {
  app.beginUndoGroup("PostFlowX ${_esc(shotName)}");

  var FIRST = ${first};
  var COUNT = ${count};
  var FPS   = ${fps};
  var TW    = ${tw};
  var TH    = ${th};
  var DURATION = COUNT / FPS;
  var PLATE_PATH = "${_esc(platePath)}";
  var TIME_REMAP = ${JSON.stringify(kfs)};

  app.newProject();
  var proj = app.project;

  // Working / display color (correct AE DOM property; guarded for older versions).
  try { proj.workingSpace = "${_esc(workingSpace)}"; } catch (e) {}

  // ── Import EXR sequence ──
  var plateItem = null;
  try {
    var io = new ImportOptions(new File(PLATE_PATH));
    io.sequence = true;
    plateItem = proj.importFile(io);
    plateItem.name = "PLATE_" + "${_esc(plateName)}";
    // Plate is scene-referred ${_esc(colorspace)}; OCIO effects below handle the transform.
  } catch (e) { alert("PostFlowX: could not import plate sequence:\\n" + PLATE_PATH); }

  // ── Optional QT reference (guide layer, excluded from render) ──
  var qtItem = null;
  ${qtRef ? `try { qtItem = proj.importFile(new ImportOptions(new File("${_esc(qtRef)}"))); qtItem.name = "QTREF_${_esc(shotName)}"; } catch (e) {}` : `// (no QT reference path provided)`}

  // ── Composition at FDL canvas size ──
  var comp = proj.items.addComp("${_esc(shotName)}_pull", TW, TH, 1.0, DURATION, FPS);
  comp.displayStartTime = FIRST / FPS;

  if (plateItem) {
    var plate = comp.layers.add(plateItem);
    plate.name = "PLATE";

    // Reframe — UNIFORM scale + centered position (never distort).
    ${baked
      ? `// Editorial framing already baked into the plate; no transform applied.`
      : `plate.property("Scale").setValue([${uniformScale}, ${uniformScale}]);
    plate.property("Position").setValue([${posX}, ${posY}]);`}

    // ── Time Remap from the frame map (ramps already resolved per frame) ──
    ${hasSpeedChange ? `if (TIME_REMAP.length > 0) {
      plate.timeRemapEnabled = true;
      var tr = plate.property("Time Remap");
      while (tr.numKeys > 0) tr.removeKey(1);
      for (var i = 0; i < TIME_REMAP.length; i++) {
        tr.addKey(TIME_REMAP[i].time_sec);
        tr.setValueAtKey(i + 1, TIME_REMAP[i].src_sec);
      }
      // Linear between keys — the per-frame map already encodes the ramp shape.
      for (var k = 1; k <= tr.numKeys; k++) {
        tr.setInterpolationTypeAtKey(k, KeyframeInterpolationType.LINEAR, KeyframeInterpolationType.LINEAR);
      }
    }` : `// No speed change — plate plays 1:1.`}

    // ── Color: OCIO chain on an adjustment layer (guarded; OCIO plugin optional) ──
    var colorAdj = comp.layers.addSolid([0, 0, 0], "COLOR_AMF", TW, TH, 1.0, DURATION);
    colorAdj.adjustmentLayer = true;
    colorAdj.moveAfter(plate);

    try {
      var cst = colorAdj.property("Effects").addProperty("OCIO Color Space Transform");
      if (cst) { cst.property("Input Color Space").setValue("${_esc(colorspace)}"); cst.property("Output Color Space").setValue("${_esc(workingSpace)}"); }
    } catch (e) {}

    ${cdl ? `try {
      var cdlFx = colorAdj.property("Effects").addProperty("OCIO CDL Transform");
      if (cdlFx) {
        var sl = ${cdlSlope}, of = ${cdlOffset}, pw = ${cdlPower};
        cdlFx.property("Slope").setValue(sl[0] + " " + sl[1] + " " + sl[2]);
        cdlFx.property("Offset").setValue(of[0] + " " + of[1] + " " + of[2]);
        cdlFx.property("Power").setValue(pw[0] + " " + pw[1] + " " + pw[2]);
        cdlFx.property("Saturation").setValue(${cdlSat});
      }
    } catch (e) {}` : `// (no auto-match CDL on this shot)`}

    ${showLutPath ? `try {
      var lut = colorAdj.property("Effects").addProperty("OCIO File Transform");
      if (lut) { lut.property("File").setValue("${_esc(showLutPath)}"); lut.property("Direction").setValue(1); }
    } catch (e) {}` : `// (no show LUT to apply — vendor OCIO config handles the look)`}
  }

  // ── QT reference guide layer at the top (not rendered) ──
  if (qtItem) {
    var qt = comp.layers.add(qtItem);
    qt.name = "QTREF_compare";
    qt.guideLayer = true;
    qt.moveToBeginning();
  }

  app.endUndoGroup();

  // Save the .aep next to this script.
  try {
    var scriptFile = new File($.fileName);
    var aep = new File(scriptFile.parent.fsName + "/${_esc(plateName)}.aep");
    proj.save(aep);
    if (!$.global.hasOwnProperty("PFX_SILENT")) alert("PostFlowX: ${_esc(shotName)} comp built and saved.\\n" + aep.fsName);
  } catch (e) {}
})();
`;
}
