// scripts/modules/nuke_import_script.js
// Build Nuke import .py script for AMF Converter
// - Creates Read node per shot from VFX_mapping.json
// - Sets first/last/origfirst/origlast when available
// - Applies look when available:
//     .cdl/.cc/.ccc -> OCIOCDLTransform (if exists)
//     .cube         -> OCIOFileTransform (if exists) else Vectorfield fallback
// - Robust to different mapping JSON shapes (shots list or dict)
//
// This module ONLY returns Python script text.
// Downloading/saving is handled by amf_convert.js (or caller).
//
// Compatibility: exports multiple aliases so existing imports keep working.

const DEFAULT_MAPPING_NAME = "VFX_mapping.json";

/**
 * Build the Nuke Python script (string).
 * @param {object} [opt]
 * @param {string} [opt.mappingName] - JSON filename expected next to script (default: VFX_mapping.json)
 * @returns {string}
 */
export function buildNukeImportScript(opt = {}) {
  const mappingName = (opt && opt.mappingName) ? String(opt.mappingName) : DEFAULT_MAPPING_NAME;

  // NOTE: Keep python as plain text, no template substitutions besides mappingName.
  // Avoid backticks inside python unless escaped.
  return `# MPS_AMF_Nuke_Import.py
# Generated by PostFlowX (AMF Converter)
# Creates Read nodes from ${mappingName} and applies Look files when available.
#
# Usage:
#   1) Put this .py next to ${mappingName} (recommended)
#   2) In Nuke: File > Run Script... (select this .py)
#
# Supports mapping shapes:
#   { "shots":[ {...}, ... ] }  OR  { "items":[...]} OR { "data":[...]} OR { "shots": {shotName:{...}} }
#
# Sequence keys supported (best-effort):
#   sequence.path / sequence.pattern / sequence.sequence / sequence.file
#   sequence.first / sequence.start / sequence.in
#   sequence.last  / sequence.end   / sequence.out
#
# Look keys supported:
#   look.path / look.file / lookPath / lookFile
#
# Look apply:
#   .cdl/.cc/.ccc -> OCIOCDLTransform (if available)
#   .cube         -> OCIOFileTransform (if available) else Vectorfield

import os
import re
import json

try:
    import nuke
except Exception:
    nuke = None

# ---- OCIO / ACES ----
# Prefers studio OCIO config B when available:
#   fn-nuke_studio-config-v1.0.0_aces-v1.3_ocio-v2.1(.ocio)
# Fallback: aces_1.2

DEFAULT_OCIO_ENV = "OCIO"  # optional override (custom config path)
PREFERRED_OCIO_CONFIGS = [
    "fn-nuke_studio-config-v1.0.0_aces-v1.3_ocio-v2.1.ocio",
    "fn-nuke_studio-config-v1.0.0_aces-v1.3_ocio-v2.1",
    "aces_1.2",
    "aces_1.3",
    "nuke-default",
]

# Working space role (ACEScg)
DEFAULT_WORKING_SPACE = "scene_linear"
DEFAULT_READ_COLORSPACE = "scene_linear"

def _set_enum(knob, candidates):
    if knob is None:
        return None
    try:
        vals = list(knob.values())
    except Exception:
        vals = []
    for c in candidates:
        if c in vals:
            try:
                knob.setValue(c)
                return c
            except Exception:
                pass
    return None

def _setup_ocio_root():
    if not nuke:
        return
    r = nuke.root()
    try:
        if "colorManagement" in r.knobs():
            r["colorManagement"].setValue("OCIO")
    except Exception:
        pass

    # Prefer built-in configs by name (no popups), fallback to custom path if provided.
    cfg_env = (os.environ.get(DEFAULT_OCIO_ENV, "") or "").strip()
    try:
        if "OCIO_config" in r.knobs():
            set_ok = _set_enum(r["OCIO_config"], PREFERRED_OCIO_CONFIGS)
            if (not set_ok) and cfg_env:
                try:
                    r["OCIO_config"].setValue("custom")
                    if "customOCIOConfigPath" in r.knobs():
                        r["customOCIOConfigPath"].setValue(cfg_env)
                except Exception:
                    pass
    except Exception:
        pass

    try:
        if "workingSpaceLUT" in r.knobs():
            _set_enum(r["workingSpaceLUT"], [DEFAULT_WORKING_SPACE, "scene_linear", "ACES - ACEScg", "ACEScg", "ACES2065-1", "linear"])
    except Exception:
        pass

DEFAULT_MAPPING_NAME = "${mappingName}"

def _msg(s):
    if nuke:
        try:
            nuke.message(str(s))
        except Exception:
            pass

def _norm_path(p):
    if not p:
        return ""
    return os.path.normpath(str(p))

def _load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def _get_script_dir():
    try:
        return os.path.dirname(os.path.abspath(__file__))
    except Exception:
        return ""

def _pick_mapping_path():
    # 1) same folder as script
    base = _get_script_dir()
    if base:
        cand = os.path.join(base, DEFAULT_MAPPING_NAME)
        if os.path.exists(cand):
            return cand

    # 2) ask user
    if not nuke:
        return ""
    p = nuke.getFilename("Select VFX_mapping.json", "*.json")
    return p or ""

def _collect_shots(data):
    shots = data.get("shots") or data.get("items") or data.get("data") or []
    if isinstance(shots, dict):
        out = []
        for k, v in shots.items():
            if isinstance(v, dict):
                vv = dict(v)
                vv.setdefault("shotName", k)
                out.append(vv)
        return out
    if isinstance(shots, list):
        return shots
    return []

def _extract_sequence_obj(shot):
    return (
        shot.get("sequence")
        or shot.get("seq")
        or shot.get("imageSequence")
        or shot.get("imgSeq")
        or {}
    )

def _extract_look_path(shot):
    look = shot.get("look") or shot.get("lookFile") or shot.get("lookPath") or {}
    if isinstance(look, dict):
        p = look.get("path") or look.get("file") or look.get("lookPath") or look.get("lookFile")
        return _norm_path(p)
    if isinstance(look, str):
        return _norm_path(look)
    return ""

def _guess_seq_fields(seq_obj):
    if not isinstance(seq_obj, dict):
        return "", None, None
    path = seq_obj.get("path") or seq_obj.get("pattern") or seq_obj.get("sequence") or seq_obj.get("file") or ""
    first = next((seq_obj[k] for k in ("first", "start", "in")  if k in seq_obj and seq_obj[k] is not None), None)
    last  = next((seq_obj[k] for k in ("last",  "end",   "out") if k in seq_obj and seq_obj[k] is not None), None)
    return _norm_path(path), first, last

def _hashes_to_printf(path):
    m = re.search(r"(#+)", path)
    if not m:
        return path
    hashes = m.group(1)
    n = len(hashes)
    return path.replace(hashes, "%%0%dd" % n, 1)

def _digits_to_printf(path):
    # name.1001.exr -> name.%04d.exr (best effort)
    m = re.search(r"(.*?)(\d+)(\.[A-Za-z0-9]+)$", path)
    if not m:
        return path
    head, digits, ext = m.group(1), m.group(2), m.group(3)
    w = len(digits)
    return f"{head}%0{w}d{ext}"

def _to_nuke_sequence_path(path):
    if not path:
        return ""
    p = path
    if "%0" in p and "d" in p:
        return p
    if "#" in p:
        return _hashes_to_printf(p)
    return _digits_to_printf(p)

def _safe_int(v):
    try:
        if v is None:
            return None
        return int(v)
    except Exception:
        try:
            return int(float(v))
        except Exception:
            return None

def _node_exists(node_class):
    try:
        getattr(nuke.nodes, node_class)
        return True
    except Exception:
        return False

def _strip_tag(tag):
    # '{ns}Name' -> 'Name'
    if not tag:
        return ''
    if '}' in tag:
        return tag.split('}', 1)[1]
    return tag

def _amf_guess_look_name(desc, tid):
    desc = (desc or '').strip()
    if desc:
        return desc

    tid = (tid or '').strip()
    if not tid:
        return ''

    # Common ACES LMT: Reference Gamut Compression
    if 'ReferenceGamutCompress' in tid:
        return 'ReferenceGamutCompress'

    # Heuristic: pick the last meaningful token (skip version-like suffixes)
    parts = [p for p in tid.split('.') if p]
    for p in reversed(parts):
        if re.match(r"^a?\d", p):
            continue
        if p.lower() in ('lmt', 'idt', 'odt', 'rrt', 'aces', 'transformid', 'v1', 'v2'):
            continue
        return p
    return ''

def _parse_triplet(txt, default):
    try:
        vals = [float(x) for x in re.split(r"[\s,]+", (txt or '').strip()) if x]
        if len(vals) >= 3:
            return [vals[0], vals[1], vals[2]]
    except Exception:
        pass
    return list(default)

def _parse_float(txt, default):
    try:
        return float(str(txt).strip())
    except Exception:
        return float(default)

def _parse_amf(amf_path):
    out = {
        'looks': [],
        'cdl': None,
        'cdl_applied': False,
        'cdl_ws': ''
    }

    try:
        import xml.etree.ElementTree as ET
        root = ET.parse(amf_path).getroot()
    except Exception:
        return out

    # Iterate lookTransform blocks (AMF v2 uses lookTransform for LMT/CDL steps)
    for lt in root.iter():
        if _strip_tag(getattr(lt, 'tag', '')) != 'lookTransform':
            continue

        applied = str(lt.attrib.get('applied', '')).strip().lower() in ('true', '1', 'yes')

        desc = ''
        tid = ''
        for ch in lt.iter():
            nm = _strip_tag(getattr(ch, 'tag', ''))
            if nm == 'description' and (ch.text or '').strip():
                desc = (ch.text or '').strip()
            elif nm == 'transformId' and (ch.text or '').strip():
                tid = (ch.text or '').strip()

        look_name = _amf_guess_look_name(desc, tid)
        if applied and look_name:
            out['looks'].append(look_name)

        # Try to extract ASC CDL inside this lookTransform
        slope = offset = power = None
        sat = None
        ws = ''

        for ch in lt.iter():
            nm = _strip_tag(getattr(ch, 'tag', ''))
            if nm in ('cdlWorkingSpace', 'cdl_working_space', 'workingSpace') and (ch.text or '').strip():
                ws = (ch.text or '').strip()
            elif nm == 'Slope' and (ch.text or '').strip():
                slope = _parse_triplet(ch.text, [1.0, 1.0, 1.0])
            elif nm == 'Offset' and (ch.text or '').strip():
                offset = _parse_triplet(ch.text, [0.0, 0.0, 0.0])
            elif nm == 'Power' and (ch.text or '').strip():
                power = _parse_triplet(ch.text, [1.0, 1.0, 1.0])
            elif nm in ('Saturation', 'SaturationValue') and (ch.text or '').strip():
                sat = _parse_float(ch.text, 1.0)

        if slope is not None or offset is not None or power is not None or sat is not None:
            out['cdl'] = {
                'slope': slope if slope is not None else [1.0, 1.0, 1.0],
                'offset': offset if offset is not None else [0.0, 0.0, 0.0],
                'power': power if power is not None else [1.0, 1.0, 1.0],
                'sat': sat if sat is not None else 1.0,
            }
            out['cdl_applied'] = applied
            out['cdl_ws'] = ws

    return out

def _create_look_chain(look_path, shot_name='SHOT'):
    """Return a list of look nodes (possibly empty).

    - .amf: applies OCIOLookTransform for applied LMT looks + OCIOCDLTransform for applied CDL
    - .cdl/.cc/.ccc: applies OCIOCDLTransform (file)
    - .cube: applies OCIOFileTransform (or Vectorfield fallback)
    """
    if not nuke or not look_path:
        return []

    ext = os.path.splitext(look_path)[1].lower()
    nodes = []

    # AMF (ACES Metadata File)
    if ext == '.amf':
        info = _parse_amf(look_path)

        # LMT look(s)
        if info.get('looks') and _node_exists('OCIOLookTransform'):
            for i, lk in enumerate(info['looks'], start=1):
                try:
                    n = nuke.nodes.OCIOLookTransform()
                    if 'look' in n.knobs():
                        n['look'].setValue(str(lk))
                    if 'in_colorspace' in n.knobs():
                        n['in_colorspace'].setValue(DEFAULT_WORKING_SPACE)
                    if 'out_colorspace' in n.knobs():
                        n['out_colorspace'].setValue(DEFAULT_WORKING_SPACE)
                    if 'ignore_errors' in n.knobs():
                        n['ignore_errors'].setValue(True)
                    try:
                        n.setName(f'LMT_{shot_name}_{i:02d}')
                    except Exception:
                        pass
                    nodes.append(n)
                except Exception:
                    pass

        # CDL (only if applied=true in AMF)
        cdl = info.get('cdl')
        if cdl and info.get('cdl_applied') and _node_exists('OCIOCDLTransform'):
            try:
                n = nuke.nodes.OCIOCDLTransform()
                if 'slope' in n.knobs():
                    n['slope'].setValue([cdl['slope'][0], cdl['slope'][1], cdl['slope'][2]])
                if 'offset' in n.knobs():
                    n['offset'].setValue([cdl['offset'][0], cdl['offset'][1], cdl['offset'][2]])
                if 'power' in n.knobs():
                    n['power'].setValue([cdl['power'][0], cdl['power'][1], cdl['power'][2]])
                if 'saturation' in n.knobs():
                    n['saturation'].setValue(float(cdl.get('sat', 1.0)))
                ws = info.get('cdl_ws') or 'ACEScct'
                if 'working_space' in n.knobs():
                    n['working_space'].setValue(ws)
                try:
                    n.setName(f'CDL_{shot_name}')
                except Exception:
                    pass
                nodes.append(n)
            except Exception:
                pass

        # If CDL exists but applied=false, drop a note (optional)
        if cdl and not info.get('cdl_applied') and _node_exists('NoOp'):
            try:
                n = nuke.nodes.NoOp()
                if 'label' in n.knobs():
                    n['label'].setValue('CDL in AMF is applied=false (not applied)')
                try:
                    n.setName(f'CDL_NOTE_{shot_name}')
                except Exception:
                    pass
                nodes.append(n)
            except Exception:
                pass

        return nodes

    # CDL / CC / CCC files
    if ext in ['.cdl', '.cc', '.ccc']:
        if _node_exists('OCIOCDLTransform'):
            try:
                n = nuke.nodes.OCIOCDLTransform()
                if 'file' in n.knobs():
                    n['file'].setValue(look_path)
                try:
                    n.setName(f'CDL_{shot_name}')
                except Exception:
                    pass
                return [n]
            except Exception:
                return []
        return []

    # LUT cube
    if ext == '.cube':
        if _node_exists('OCIOFileTransform'):
            try:
                n = nuke.nodes.OCIOFileTransform()
                if 'file' in n.knobs():
                    n['file'].setValue(look_path)
                elif 'lut' in n.knobs():
                    n['lut'].setValue(look_path)
                try:
                    n.setName(f'LUT_{shot_name}')
                except Exception:
                    pass
                return [n]
            except Exception:
                return []

        # Fallback: Vectorfield
        if _node_exists('Vectorfield'):
            try:
                n = nuke.nodes.Vectorfield()
                if 'vfield_file' in n.knobs():
                    n['vfield_file'].setValue(look_path)
                elif 'file' in n.knobs():
                    n['file'].setValue(look_path)
                try:
                    n.setName(f'LUT_{shot_name}')
                except Exception:
                    pass
                return [n]
            except Exception:
                return []

        return []

    # Unknown look type
    return []

def _layout_nodes(nodes, start_x=0, start_y=0, y_step=140):
    x, y = start_x, start_y
    for n in nodes:
        try:
            n.setXpos(x)
            n.setYpos(y)
            y += y_step
        except Exception:
            pass

def _create_chain_for_shot(shot, x=0, y=0):
    if not nuke:
        return 0

    shot_name = shot.get("shotName") or shot.get("shot") or shot.get("name") or "SHOT"

    seq_obj = _extract_sequence_obj(shot)
    seq_path, first, last = _guess_seq_fields(seq_obj)
    seq_path = _to_nuke_sequence_path(seq_path)

    if not seq_path:
        return 0

    first_i = _safe_int(first)
    last_i  = _safe_int(last)

    read = nuke.nodes.Read(name=f"READ_{shot_name}")
    read["file"].setValue(seq_path)

    try:
        if 'colorspace' in read.knobs():
            read['colorspace'].setValue(DEFAULT_READ_COLORSPACE)
    except Exception:
        pass

    if first_i is not None and last_i is not None:
        for k in ["first", "last", "origfirst", "origlast"]:
            if k in read.knobs():
                if k in ["first", "origfirst"]:
                    read[k].setValue(first_i)
                else:
                    read[k].setValue(last_i)

    look_path = _extract_look_path(shot)
    look_nodes = _create_look_chain(look_path, shot_name=shot_name) if look_path else []

    nodes = [read]
    prev = read
    for ln in (look_nodes or []):
        try:
            ln.setInput(0, prev)
        except Exception:
            pass
        nodes.append(ln)
        prev = ln

    _layout_nodes(nodes, start_x=x, start_y=y)

    # Optional Backdrop
    try:
        bd = nuke.nodes.BackdropNode()
        bd["label"].setValue(f"{shot_name}")
        if "note_font_size" in bd.knobs():
            bd["note_font_size"].setValue(28)
        bd.setXpos(x - 40)
        bd.setYpos(y - 60)
        if "bdwidth" in bd.knobs():  bd["bdwidth"].setValue(520)
        if "bdheight" in bd.knobs(): bd["bdheight"].setValue(240 if (look_nodes and len(look_nodes) > 0) else 180)
    except Exception:
        pass

    return 1

def run():
    if not nuke:
        raise RuntimeError("This script must be run inside Nuke.")

    # Set project to Netflix ACES 2.0 OCIO (if OCIO env var is present)
    _setup_ocio_root()

    mapping_path = _pick_mapping_path()
    if not mapping_path or not os.path.exists(mapping_path):
        _msg("Mapping json not found. Export VFX_mapping.json from AMF tab first.")
        return

    try:
        data = _load_json(mapping_path)
    except Exception as e:
        _msg(f"Failed to read mapping json:\\n{e}")
        return

    shots = _collect_shots(data)
    if not shots:
        _msg("No shots found in mapping json.")
        return

    created = 0
    x0, y0 = 0, 0
    col = 0
    row = 0
    col_w = 620
    row_h = 320

    for s in shots:
        # Only create when sequence exists
        seq_obj = _extract_sequence_obj(s)
        seq_path, _, _ = _guess_seq_fields(seq_obj)
        if not seq_path:
            continue

        x = x0 + (col * col_w)
        y = y0 + (row * row_h)

        created += _create_chain_for_shot(s, x=x, y=y)

        col += 1
        if col >= 2:
            col = 0
            row += 1

    _msg(f"Imported {created} shot(s) from:\\n{mapping_path}")

# Auto-run when executed via File > Run Script...
try:
    run()
except Exception:
    pass
`;
}

/* ---- Backward-compatible aliases (in case your caller uses old names) ---- */

export function getNukeImportScript(opt = {}) {
  return buildNukeImportScript(opt);
}

export function buildNukePy(opt = {}) {
  return buildNukeImportScript(opt);
}

export const NUKE_IMPORT_PY = buildNukeImportScript({ mappingName: DEFAULT_MAPPING_NAME });

export default buildNukeImportScript;
